/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Diniz
 */
public class atualizar extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public atualizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_atualiza = new javax.swing.JFormattedTextField();
        voltar_remover = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        peso_atualiza = new javax.swing.JFormattedTextField();
        novopeso_atualiza = new javax.swing.JFormattedTextField();
        atualizar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DE ATUALIZACAO");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        id_atualiza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        id_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_atualizaActionPerformed(evt);
            }
        });
        getContentPane().add(id_atualiza);
        id_atualiza.setBounds(150, 50, 80, 22);

        voltar_remover.setText("VOLTAR");
        voltar_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_removerActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_remover);
        voltar_remover.setBounds(190, 260, 90, 23);

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setText("ID");
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(110, 50, 30, 22);

        jFormattedTextField7.setEditable(false);
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField7.setText("NOVO PESO");
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7);
        jFormattedTextField7.setBounds(20, 190, 90, 22);

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setText("PESO ATUAL");
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(20, 160, 90, 22);

        peso_atualiza.setEditable(false);
        peso_atualiza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        peso_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_atualizaActionPerformed(evt);
            }
        });
        getContentPane().add(peso_atualiza);
        peso_atualiza.setBounds(120, 160, 80, 22);

        novopeso_atualiza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        novopeso_atualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novopeso_atualizaActionPerformed(evt);
            }
        });
        getContentPane().add(novopeso_atualiza);
        novopeso_atualiza.setBounds(120, 190, 80, 22);

        atualizar.setText("ATUALIZAR");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(290, 260, 100, 23);

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(240, 50, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_atualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_atualizaActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void voltar_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_removerActionPerformed
    javax.swing.SwingUtilities.getWindowAncestor(voltar_remover).dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_removerActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void peso_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_atualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_atualizaActionPerformed

    private void novopeso_atualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novopeso_atualizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novopeso_atualizaActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
            String jdbcUrl = "jdbc:mysql://localhost:3306/fazenda?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Scanner teclado = new Scanner(System.in);
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            
            String tabela = "fazenda.animais";
            int id=Integer.parseInt(id_atualiza.getText());
            double npeso =Double.parseDouble(novopeso_atualiza.getText().replace(",", "."));
            
            if(npeso<=0){
                JOptionPane.showMessageDialog(null, "Entre com um peso valido ");
            }
            else{
                
            String selectByIdQuery = "SELECT * FROM " + tabela + " WHERE id = ?";
            PreparedStatement psSelectById = connection.prepareStatement(selectByIdQuery);
            psSelectById.setInt(1, id);
            ResultSet resultadoId = psSelectById.executeQuery();           
            
            if (resultadoId.next()) {
                
            int opcao = JOptionPane.showConfirmDialog(null,"Deseja confirmar essa atualizacao ?","Confirmacao",JOptionPane.YES_NO_OPTION);
            
            if(opcao == JOptionPane.YES_OPTION){

            String updateQuery = "UPDATE " + tabela + " SET peso = ? WHERE id = ?";
            PreparedStatement psAtualizar = connection.prepareStatement(updateQuery);
            psAtualizar.setDouble(1, npeso);
            psAtualizar.setInt(2, id);
            psAtualizar.executeUpdate();       
            JOptionPane.showMessageDialog(null, "Peso atualizado com sucesso!");
            
            peso_atualiza.setText(novopeso_atualiza.getText());
            novopeso_atualiza.setText("");
        }
        else{            
        } } 
            else {
            JOptionPane.showMessageDialog(null, "Animal nao encontrado !");
            peso_atualiza.setText("");
            novopeso_atualiza.setText("");
            }           }
            } catch (SQLException e) {
            e.printStackTrace();}
            

// TODO add your handling code here:
    }//GEN-LAST:event_atualizarActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
            String jdbcUrl = "jdbc:mysql://localhost:3306/fazenda?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Scanner teclado = new Scanner(System.in);
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            
            String tabela = "fazenda.animais";
            int id=Integer.parseInt(id_atualiza.getText());
            
            String selectByIdQuery = "SELECT * FROM " + tabela + " WHERE id = ?";
            PreparedStatement psSelectById = connection.prepareStatement(selectByIdQuery);
            psSelectById.setInt(1, id);
            ResultSet resultadoId = psSelectById.executeQuery();
                      
            if (resultadoId.next()){
              String peso = resultadoId.getString("peso");
              peso_atualiza.setText(peso);
              novopeso_atualiza.setText("");

            }
            else {
              JOptionPane.showMessageDialog(null, "Animal nao encontrado !");
              peso_atualiza.setText("");
              novopeso_atualiza.setText("");
            
            }
            } catch (SQLException e) {
            e.printStackTrace();}     
        






// TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizar;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField id_atualiza;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField novopeso_atualiza;
    private javax.swing.JFormattedTextField peso_atualiza;
    private javax.swing.JButton voltar_remover;
    // End of variables declaration//GEN-END:variables
}
