/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menus;

import static java.lang.System.exit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Diniz
 */
public class consultar_remover extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public consultar_remover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        id_consulta = new javax.swing.JFormattedTextField();
        nome_consulta = new javax.swing.JFormattedTextField();
        raca_consulta = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        voltar_remover = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jFormattedTextField7 = new javax.swing.JFormattedTextField();
        jFormattedTextField8 = new javax.swing.JFormattedTextField();
        jFormattedTextField9 = new javax.swing.JFormattedTextField();
        sexo_consulta = new javax.swing.JFormattedTextField();
        categoria_consulta = new javax.swing.JFormattedTextField();
        peso_consulta = new javax.swing.JFormattedTextField();
        remover_consulta = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TELA DE CONSULTA");
        setMinimumSize(new java.awt.Dimension(600, 400));
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        id_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        id_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(id_consulta);
        id_consulta.setBounds(150, 50, 80, 22);

        nome_consulta.setEditable(false);
        nome_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_consultaActionPerformed(evt);
            }
        });
        nome_consulta.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nome_consultaPropertyChange(evt);
            }
        });
        getContentPane().add(nome_consulta);
        nome_consulta.setBounds(80, 140, 160, 22);

        raca_consulta.setEditable(false);
        raca_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raca_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(raca_consulta);
        raca_consulta.setBounds(80, 170, 160, 22);

        jFormattedTextField4.setEditable(false);
        jFormattedTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField4.setText("RACA");
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField4);
        jFormattedTextField4.setBounds(20, 170, 50, 22);

        voltar_remover.setText("VOLTAR");
        voltar_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar_removerActionPerformed(evt);
            }
        });
        getContentPane().add(voltar_remover);
        voltar_remover.setBounds(190, 260, 90, 23);

        jFormattedTextField5.setEditable(false);
        jFormattedTextField5.setText("ID");
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5);
        jFormattedTextField5.setBounds(110, 50, 30, 22);

        jFormattedTextField6.setEditable(false);
        jFormattedTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField6.setText("CATEGORIA");
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField6);
        jFormattedTextField6.setBounds(20, 110, 80, 22);

        jFormattedTextField7.setEditable(false);
        jFormattedTextField7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextField7.setText("NOME");
        jFormattedTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField7);
        jFormattedTextField7.setBounds(20, 140, 50, 22);

        jFormattedTextField8.setEditable(false);
        jFormattedTextField8.setText("SEXO");
        jFormattedTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField8);
        jFormattedTextField8.setBounds(20, 200, 50, 22);

        jFormattedTextField9.setEditable(false);
        jFormattedTextField9.setText("PESO");
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField9);
        jFormattedTextField9.setBounds(20, 230, 50, 22);

        sexo_consulta.setEditable(false);
        sexo_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        sexo_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexo_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(sexo_consulta);
        sexo_consulta.setBounds(80, 200, 80, 22);

        categoria_consulta.setEditable(false);
        categoria_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        categoria_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoria_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(categoria_consulta);
        categoria_consulta.setBounds(110, 110, 80, 22);

        peso_consulta.setEditable(false);
        peso_consulta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        peso_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peso_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(peso_consulta);
        peso_consulta.setBounds(80, 230, 80, 22);

        remover_consulta.setText("REMOVER");
        remover_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remover_consultaActionPerformed(evt);
            }
        });
        getContentPane().add(remover_consulta);
        remover_consulta.setBounds(290, 260, 100, 23);

        consultar.setText("CONSULTAR");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        getContentPane().add(consultar);
        consultar.setBounds(240, 50, 110, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 520, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_consultaActionPerformed

    private void nome_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_consultaActionPerformed


// TODO add your handling code here:
       
    }//GEN-LAST:event_nome_consultaActionPerformed

    private void raca_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raca_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raca_consultaActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void voltar_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar_removerActionPerformed
    javax.swing.SwingUtilities.getWindowAncestor(voltar_remover).dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_voltar_removerActionPerformed

    private void nome_consultaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nome_consultaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_consultaPropertyChange

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jFormattedTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField7ActionPerformed

    private void jFormattedTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField8ActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void sexo_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexo_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexo_consultaActionPerformed

    private void categoria_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoria_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoria_consultaActionPerformed

    private void peso_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peso_consultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peso_consultaActionPerformed

    private void remover_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remover_consultaActionPerformed
            String jdbcUrl = "jdbc:mysql://localhost:3306/fazenda?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Scanner teclado = new Scanner(System.in);
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            
            String tabela = "fazenda.animais";
            int id=Integer.parseInt(id_consulta.getText());

            String selectByIdQuery = "SELECT * FROM " + tabela + " WHERE id = ?";
            PreparedStatement psSelectById = connection.prepareStatement(selectByIdQuery);
            psSelectById.setInt(1, id);
            ResultSet resultadoId = psSelectById.executeQuery();
            
        if (resultadoId.next()) {            
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja remover esse animal ?","Confirmacao",JOptionPane.YES_NO_OPTION);
        if(opcao == JOptionPane.YES_OPTION){
          
            String deleteQuery = "DELETE FROM " + tabela + " WHERE id = ?";
            PreparedStatement psRemover = connection.prepareStatement(deleteQuery);
            psRemover.setInt(1, id);
            psRemover.executeUpdate();
            JOptionPane.showMessageDialog(null, "Animal removido com sucesso!");
            
              categoria_consulta.setText("");
              nome_consulta.setText("");
              raca_consulta.setText("");
              sexo_consulta.setText("");
              peso_consulta.setText("");
        }
        else{

        }    } 
            else {
            JOptionPane.showMessageDialog(null, "Animal nao encontrado !");
            categoria_consulta.setText("");
            nome_consulta.setText("");
            raca_consulta.setText("");
            sexo_consulta.setText("");
            peso_consulta.setText("");

            }            
            }catch (SQLException e) {
            e.printStackTrace();}
        
// TODO add your handling code here:
    }//GEN-LAST:event_remover_consultaActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
               
        
            String jdbcUrl = "jdbc:mysql://localhost:3306/fazenda?serverTimezone=America/Sao_Paulo";
            String username = "root";
            String password = "root";
            
            try (Scanner teclado = new Scanner(System.in);
            Connection connection = DriverManager.getConnection(jdbcUrl, username, password)) {
            
            int id=Integer.parseInt(id_consulta.getText());
            
            String tabela = "fazenda.animais";
            
            String selectByIdQuery = "SELECT * FROM " + tabela + " WHERE id = ?";
            PreparedStatement psSelectById = connection.prepareStatement(selectByIdQuery);
            psSelectById.setInt(1, id);
            ResultSet resultadoId = psSelectById.executeQuery();
            
            if (resultadoId.next()) {
              
              String especie = resultadoId.getString("especie");            
              String raca = resultadoId.getString("raca");  
              String nome = resultadoId.getString("nome");
              String sexo = resultadoId.getString("sexo");
              String peso = resultadoId.getString("peso");
              
              categoria_consulta.setText(especie);
              nome_consulta.setText(nome);
              raca_consulta.setText(raca);
              sexo_consulta.setText(sexo);
              peso_consulta.setText(peso);

                        } 
            else {
              JOptionPane.showMessageDialog(null, "Animal nao encontrado !");
              categoria_consulta.setText("");
              nome_consulta.setText("");
              raca_consulta.setText("");
              sexo_consulta.setText("");
              peso_consulta.setText("");

                        }
            } catch (SQLException e) {
            e.printStackTrace();}
    }              
            
            
       /* 



        // TODO add your handling code here:
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(consultar_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(consultar_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(consultar_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(consultar_remover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new consultar_remover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField categoria_consulta;
    private javax.swing.JButton consultar;
    private javax.swing.JFormattedTextField id_consulta;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField nome_consulta;
    private javax.swing.JFormattedTextField peso_consulta;
    private javax.swing.JFormattedTextField raca_consulta;
    private javax.swing.JButton remover_consulta;
    private javax.swing.JFormattedTextField sexo_consulta;
    private javax.swing.JButton voltar_remover;
    // End of variables declaration//GEN-END:variables
}
